### ISSUE TITLE
new case - plugin for WordPress & WooCommerce

### ISSUE THREAD

**Issue by aiiddqd** [TelePay-cash/telepay-php#1]
hi there )

thank you for your product.
I used it and made a plugin for WordPress and WooCommerce https://github.com/uptimizt/ton-gateway

**Comment by CarlosLugones** [comment]
Hey @uptimizt! Thank you for this! :clap:

We actually have a Woocommerce plugin created but haven't released it.

Can you contact me at ceo@telepay.cash, so we can arrange to launch yours + ours? I'm taking a look at your plugin now.

Greetings from our team!
